### ISSUE TITLE
Error: The dice roll formula 1d10 + 0[Ref] + 0[Swordmanship] did not produce a numeric outcome when making weapons

### ISSUE THREAD

**Issue by RedCap2317** [AnthonyMonette/TheWitcherTRPG#127]
![image](https://user-images.githubusercontent.com/82011599/139574416-6ac9d27e-c86f-4af0-ae18-5960b0b1ebfe.png)

**Comment by AnthonyMonette** [comment]
can you send me a screenshot of the weapon details that you where trying to roll?

**Comment by RedCap2317** [comment]
Yea sure.
![image](https://user-images.githubusercontent.com/82011599/139723577-32671098-a87b-4443-83df-7f989c433313.png)

**Comment by AnthonyMonette** [comment]
in the error logs it seems that you have 180 in REF i'm pretty sure it's not the case but maybe there a problem here.  Could you send me the Json of your Character? in the actors items , right click on your actor and the Export Data and send me the file it downloaded I'll try to reproduce the problem since for me it does'nt seems to have the error

**Comment by RedCap2317** [comment]
Sure! I was just creating a starting enemy mob and was wondering if I did something wrong. 
[fvtt-Actor-Character.zip](https://github.com/AnthonyMonette/TheWitcherTRPG/files/7456494/fvtt-Actor-Character.zip)

**Comment by AnthonyMonette** [comment]
It's strange  I just tried with your character and it seems to work fine what version of foundry are you using ?

**Comment by RedCap2317** [comment]
0.7.10 for Foundry

**Comment by RedCap2317** [comment]
Thinking about it could be a version incompatibility.

**Comment by RedCap2317** [comment]
Seems that fixed it, I reinstalled my Foundry to the latest version. 

Thanks for the help debugging!
