### ISSUE TITLE
Display attack details in applying damage diaog box

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#166]
in the event of damage, transfer the hit point and the type of damage and any silver damage. **What I mean is that it is not visible in the dialog box**

**Comment by AnthonyMonette** [comment]
Sorry missclicked.  Can you be a little more precise.  When applying damage,  you would like to see total damage, and silver damage ?
it is displayed here:
![image](https://user-images.githubusercontent.com/12412198/145456985-293a2044-8695-4d70-b9be-b9f5c5f138b5.png)

**Comment by Ulvtand** [comment]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/82996726/145523221-c5f7c567-d4e1-4527-baa1-b27001fc9fdc.png">
As you can see, hit location etc. is not visible in the dialog box

**Comment by Dillatr** [comment]
The hit location is automatically generated in the attack roll and will be assumed to be the location for the damage
![image](https://user-images.githubusercontent.com/91529833/145528135-2dd76fe4-06ca-4cd6-aed1-d1e5672215c1.png)

The "Change The Location" drop-down box allows you to update the damage location due to a critical wound if the original hit location was randomly decided

**Comment by Ulvtand** [comment]
Yes I know, but the wish is that it says in the dialog as well. :)
