### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by Seanboy21** [AnthonyMonette/TheWitcherTRPG#173]
Hi!
Sorry do know where to post, but when creating a character do we drag and drop or write it up from scratch? Just wondering...

**Comment by AnthonyMonette** [comment]
Hello This is not an issue but more of a question.  I'll answer here but for next time you can contact me on discord :TechAntho#8519  or write in the foundry discord or I'm also on the R Tsalorian discord
To answer your question it's really up to you. At first it would be from scratch since you don't have anything. But It's preferable to create items, spells and everyting separatly to make them reusable.  Of course you can also click on the + buttons and edit directly in the character sheet to create a new item

**Comment by Seanboy21** [comment]
Thank you very much
