### ISSUE TITLE
on block parry 

### ISSUE THREAD

**Issue by Ulvtand** [AnthonyMonette/TheWitcherTRPG#178]
what has been used for defense must not have its rel reduced

**Comment by Dillatr** [comment]
Hi, are you saying that when you parry, the issue is that the Rel. is being reduced when it shouldn't be?

I've given it a test on my client and it appears to work correctly with blocks reducing Rel. and Parries keeping it the same. Have you made sure that the right weapon/item is being used for the defence is selected in the defence prompt?

![image](https://user-images.githubusercontent.com/91529833/145527150-d0017ba0-90a7-4505-9342-d4561da13a82.png)

**Comment by Dillatr** [comment]
On a side note, I've noticed that using the block defence action automatically reduced weapon/shield Rel. regardless if the defence was successful or not when it should only be reduced after a successful block.

I'm not sure the difficulty of writing code to get the defence roll to compare itself against the attack roll which prompted the defence.
![image](https://user-images.githubusercontent.com/91529833/145527409-1afa548b-62b9-4947-bae8-cace3011d5c5.png)

An alternative could be to have an option to right-click a block defence chat message to reduce the Rel. rather than needing to revert the Rel. reduction manually each time a block failed.

**Comment by Ulvtand** [comment]
To reduce all misunderstandings, we will open a discussion in discord and with a split screen?
