### ISSUE TITLE
What are the effects of the skills checkboxes ?

### ISSUE THREAD

**Issue by JhaelenTerear** [AnthonyMonette/TheWitcherTRPG#209]
Hello,

What are the effects of the skills checkboxes ? If it is what I'm thinking, maybe the TotalProfSkill doesn't sum it right ?

![image](https://user-images.githubusercontent.com/58259514/149160138-8c4a20bd-05f4-4937-a9c6-ce47e048011c.png)

**Comment by JhaelenTerear** [comment]
Okay I noted that the second total is for the skills in "Race & Profession" tab. But my question remains for the checkboxes :) !

**Comment by AnthonyMonette** [comment]
Hello!  Those checkbox are to visualy simplify the character creation.  When you create your characters, you can check the skills from your profession and then place all of your skill points in the one in red. Then you would have the learned checkbos that make sure to differentiates the learned skills, which you cannot put IP in them, since they can only be trained with external help(Teacher, book, etc) or self-tought up to level 2

**Comment by JhaelenTerear** [comment]
Ok so no automatic actions when checked or not. Only visual indications, it's perfect ! Thanks for your answer.
