### ISSUE TITLE
Unable to delete empty folders

### ISSUE THREAD

**Issue by gchaquinga** [AnthonyMonette/TheWitcherTRPG#215]
I couldn't delete an empty folder I created. I test to delete folders in other systems from foundryvtt and this issue was not present. If I log out and close the world, the only thing that I can do is change the name. However, if I tried to delete the folder after this, I am unable to edit the name again until I log out and reopen the world.

I also notice there is a message when this error is happening and I get out of the world. I attached an image to this notification
![foundry error](https://user-images.githubusercontent.com/74106960/149606477-322b458b-0e64-4311-8bee-8397a36aaa22.png)
.

**Comment by AnthonyMonette** [comment]
could you press F12 and se if any error pops up in the console ?

**Comment by gchaquinga** [comment]
Hi, Anthony.

I found 1 error and 2 issues.

1. This is the error:

**Unchecked runtime.lastError: The message port closed before a response was received.**

2. These are the 2 issues with the same message:

**Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform**

Sources: 

content-script-utils.js:1
adblock-functions.js:1


Best regards,

Guillermo

**Comment by gchaquinga** [comment]
Another detail on this. A few minutes after trying to delete the folder I get kicked out of the world and it shuts down.

**Comment by Ulvtand** [comment]
Excuse me for getting involved, but I wonder if you use any hosting service, such as Foundry Server, Molten Hosting or The Forge?

**Comment by gchaquinga** [comment]
No problem, UIvtand. Any help is appreciated. I use a private server I rent from OVHcloud. I wouldn't know if that would affect me because for the past year I was running Cyberpunk RED and there were no issues like this. I tried to delete folders the same way in that other system yesterday and there were no issues.

I know little to nothing about coding, sorry; a friend of mine who does this for a living is the one that set up the server for me. He took a look at the issue and he was going to provide later his findings.

**Comment by Ulvtand** [comment]
I myself have the same type of problem: I can not delete folder on the server (I have also tried to use Filezilla, without success), but my problem is not in Foundry. I have turned to the admin for Molten Hosting and they deleted the folder.

Since I switched to v9, there has been trouble with the communication with the server and I have sometimes received a few hundred errors, with similar content: "could not reach the server". If I then hit F5, the error counter is down to 0

I also thought that in the picture it says that "..game sever is ..." then I wonder if the problem really lies in Witcher. Can you take a picture from the console (error) after receiving the message "..game severn is ..."

**Comment by AnthonyMonette** [comment]
Yeah, this seems to be a hosting issue not a system issue.  I'm gonna close this
