### ISSUE TITLE
Witcher's Journal Monster Base

### ISSUE THREAD

**Issue by Batziy** [AnthonyMonette/TheWitcherTRPG#60]
In the witcher's journal. Creatures ATK Base and Defence Base is different from stat+skill.

Example: Giant Celeripede have ATK Base 10 for bite. but have 7 in ref and 0 in mele. Reposition Base 11 but Dex 6 and Atletics 11.

Maby we could add a Base override box?

**Comment by Xywenx** [comment]
How I saw it, it's that the ATK and Defense Base is derived from the appropriate Skill, so let's take Earth Elemental, it has Block Base and ATK Base of 14. It's REF is 6. That means it's meele would be 8, even though it's not listed, since Attack and Block uses melee. Though for the Giant Centipede I have noticed that Block Base and ATK Base are different for some reason? Maybe a mistake in the book? Most other creatures have same Block Base as ATK Base, meaning you can just put the appropriate number into melee and it will calculate it. For the Dodge Skill you simply but Dodge Base - REF into the Dodge Skill. Reposition Base is derived from Athletics + DEX, it should automaticly calculate it correctly if you put in the right number for Athletics. So for Earth Elemental, it has Dex of 5 and Athletics Skill Base of 9, meaning you put 4 into Athletics, because Base already takes Dex into account.

**Comment by Batziy** [comment]
Problem with Giant centipede is that it has Dex 6 and Athletics 11 so for reposition it's base is 17. I guess you can change it on the fly but it rubs we the wrong way. 

also noticed that Succubus have 3 attack's with 2 different ATK base. Kick and Punch mabye should use brawl instead of melee but the they have 16 in Brawling and Ref 7 so same problem there.

Mabye it would be easier to just change it so every monster have a fillable for doge, repo, block, and every attack have a ATK base box instead?

Feel like this change will stay for the future and what I have read is that they have done this so monster can have higher stats but nots necessary be better in combat.

**Comment by AnthonyMonette** [comment]
@Batziy Actually the stats are already taken in account in the Skill base table.  So the giant centipiede will have a base of 11 for reposition. not 17

For the succubi  Each attack is listed with its AttackBase, which incorporates the appropriate statistic and skill to roll an attack.  There might be some different skill used for those attacks.

**Comment by Batziy** [comment]
Yeah the book says it's base is 11 and the book also says its Dex is 6 and Athletics is 11. So if you want to climb with the centipede you roll d10+Dex(6)+Atl(11) and the someone hit you at the top and you want to reposition. You roll d10+Dex(6)+Atl(5). The GM have to manually go in and change the stat between the rolls.

This is not a huge problem but I feel if we can make the job easier for the GM we should do so.

Yeah you could connect the headbutt to the word skill but it's feel's kinda hacky. and if your sucuby want to pick up a word an PC dropped you have to decide if they really have 6 in swordsmanship.

**Comment by Xywenx** [comment]
@Batziy The book says it's Athletics Skill Base is 11, not the Skill itself. Skill and Skill Base are seperate. Skill Base is Skill + Stat. So the Giant Centinpede does not have Athletics of 11. It has Athletics of 5, because Athletics Skill Base = Dex + Athletics, so 11 = 6 + 5.
If you want to climb, you roll d10+dex(6)+atl(5) OR you roll d10+atl skill base (11). GM doesn't have to change any stats.

Hoped this help explain it. Check out the beginning of the Witcher's Journal book, it says how Skill Base etc. works.

**Comment by Batziy** [comment]
oh shit. totally missed it was skill base and not skill. my bad.

This kind of change the problem though. will be a lot of calculation to determent the correct stat for the gm to put into the sheet. kinda depends on how they want to have it in future books.
